### ISSUE TITLE
Response 401 Login failed on encrypted call

### ISSUE THREAD

**Issue by thrillfall** [xmikos/fdroiddata#1]
When i try to call another signal user over signal i get "Login Failed!" Error Message and the call aborts.
Text messages do work without a problem. I have already tried resolve this issue by unregistering my mobile number via the webinterface and reregistering inside signal. I still get the error.

[Debug log](https://gist.github.com/anonymous/fb00343e0098cef4de89). You'll find this Exception in line 881:

```
W/InitiatingCallManager(21045): org.thoughtcrime.redphone.signaling.LoginFailedException: Initiate threw 401
W/InitiatingCallManager(21045):     at org.thoughtcrime.redphone.signaling.SignalingSocket.initiateConnection(SignalingSocket.java:185)
W/InitiatingCallManager(21045):     at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:77)
```

When i try to call my number from another signal instance (from Google Playstore) then an error message is displayed saying that the called party (me) is not capable of encrypted calls.
But when i use the librephone app [(xmikos)](https://eutopia.cz/experimental/fdroid/repo) on my mobile to call the other way around it works very well.

Are there changes in the connection logic on the redphone part?

**Comment by xmikos** [comment]
If you are using LibreSignal from my main repository (independent build from official Signal sources), it should work without problems (but you need Google Play Services). If you are using websocket-fork from my experimental repository, it is currently broken (see this upstream pull request/issue of websocket-fork: https://github.com/JavaJens/TextSecure/pull/38).

**Comment by xmikos** [comment]
Problem is that registration with RedPhone server in Signal seems to require GCM, it is not possible to use it only with websockets (like it is possible with TextSecure server). Even if RedPhone + TextSecure has been merged into Signal, it still uses two completely different servers for text messages and for voice calls (and only text messages server is websocket-capable).

**Comment by thrillfall** [comment]
Thank you for clearing that up. This is an information that is nowhere to be found.
Thank you very much for your work to provide a non gcm depended signal version.

**Comment by thrillfall** [comment]
I moved to the "original" (gcm) signal build from f-droid repo. Along with Xposure and FakeGApps i now can text and place and receive calls via signal.
