### ISSUE TITLE
Fingerprint on website

### ISSUE THREAD

**Issue by dotlambda** [xmikos/fdroiddata#10]
Please consider putting your signing fingerprints on the website, so we can fill out all fields in F-Droid's "Add new repository" dialog.

**Comment by xmikos** [comment]
Fingerprints are already on the website. They are part of the links to repositories (e.g. `https://eutopia.cz/fdroid/repo?fingerprint=A0E4D1D912D8B81809AB18F5B7CF562CD1A10533ED4F7B25E595ABC8D862AD87`). If you click on them in web browser on Android, repository will be added to F-Droid with the fingerprint field pre-filled.
