### ISSUE TITLE
Updates for LibreSignal?

### ISSUE THREAD

**Issue by aphirst** [xmikos/fdroiddata#11]
I know that at the moment this entire situation is all a big complicated mess ([This thread](https://github.com/JavaJens/TextSecure/issues/72) is enough evidence of that), but I was surprised to notice that the F-Droid repo still only has 3.9.x, when the official app is now at 3.12.x. For the versions where all the Google API stuff is removed, this makes sense, but I'm running my device with microG and so on and have GCM (and maps API "without Google" stuff etc.) set up and working, so the "vanilla" LibreSignal ought (unless there's something else about the newer versions that I've missed/misunderstood) to be able to run.

I don't expect a response right away, but I thought I should pin something up all the same. Looking forward for when there's the chance for a reply.

**Comment by relyt29** [comment]
side note, if you have microG you shouldn't need any of this stuff at all, you should be able to build from upstream and it should run on your phone no issues, from what I've heard/read

**Comment by aphirst** [comment]
@f41c0r Sure, but the point at least for me and users like me is that F-Droid is the only really convenient way to get Signal via an actual "distribution mechanism", as otherwise it has to be from Google Play, or manually built (and then no update mechanism).

[Post edited, things I write when half asleep often do not make sense.]

**Comment by xmikos** [comment]
I have published update, sorry that it took that long (I didn't have too much time lately to review changes in new version). Now it is finally done. I hope it will be quicker next time...

**Comment by aphirst** [comment]
No problem. I, and many others, appreciate the effort you put in.

**Comment by herbsmn** [comment]
9 days and counting. Please do one last LibreSignal update in the next 9 days. https://github.com/LibreSignal/LibreSignal/issues/42

**Comment by zoff99** [comment]
just a hint:

https://github.com/WhisperSystems/Signal-Android/pull/5521/files

for the official repo on github and put my circle.yml file into it.
then you can build the official app yourself, on circleCI (you dont need any build server) !!

example result:
https://circleci.com/gh/zoff99/Signal-Android/14#artifacts

**Comment by xmikos** [comment]
@zoff99 Thanks, CircleCI is interesting, but I don't trust build servers that are not in my control. Definitely not for security / privacy related apps.

@herbsmn I will update (and keep updated in the future) builds from official Signal sources in my main repository, but builds of LibreSignal (WebSocket fork) in my experimental repository depends on LibreSignal code being updated, and that is uncertain for now...

**Comment by zoff99** [comment]
@xmikos this was not for you :-)
but for people who want to build from source, and do NOT have any server available.
maybe you can merge the circle.yml file just in case. it does not do anything bad when it's in the repo
