### ISSUE TITLE
LibreSignal

### ISSUE THREAD

**Issue by mimi89999** [xmikos/fdroiddata#13]
Will you use my fork: https://github.com/LibreSignal/LibreSignal in your experimental repo?

**Comment by xmikos** [comment]
Hi, what changes are you planning in comparison with JavaJens fork? Is there some roadmap or TODO list? Are you open for patches adding new features (like my patch for enabling WebSocket-only mode at runtime instead of compile-time)?

**Comment by mimi89999** [comment]
The current roadmap is to get LibreSignal accepted in the official F-Droid repo and to pull updates from upstream. I removed Location and the ability to use GCM from LibreSignal because they needed non-free libraries. The app is WebSocket-only.

> Are you open for patches adding new features

Yes under the condition that they don't require non-free libraries.

> like my patch for enabling WebSocket-only mode at runtime instead of compile-time

I think your patch should be mered in JavaJens fork, but not here since there is no GCM support...

**Comment by xmikos** [comment]
@mimi89999 I have reviewed your changes and it seems good. But I don't like removing Location sharing support... maybe it could be replaced by some shim from microG project? Did you look into this possibility?

**Comment by mimi89999** [comment]
I will look into that later...

**Comment by mimi89999** [comment]
Implementing completly free/libre location support won't be easy and I don't think it's so important for me to work on it, but I'm open to PR.

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/issues/#11

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/issues/11

**Comment by mimi89999** [comment]
@xmikos Have you received my reply to your email?

**Comment by mimi89999** [comment]
Also, I will change the package name: https://github.com/LibreSignal/LibreSignal/issues/12

**Comment by xmikos** [comment]
Finally done :-)

**Comment by SecUpwN** [comment]
Thanks for the wonderful collaboration @mimi89999 and @xmikos! :+1:

**Comment by mimi89999** [comment]
LibreSignal is not in the F-Droid archive repo because they had problems building it...
