### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by thrillfall** [xmikos/fdroiddata#2]
I'm using v3.3.1 libresignal with fakeGapps and it is working great. Thank you for building signal and making it available in an f-droid repo. I would like to know if you plan on building the latest version (3.4.x)? And also if you plan to keep up the repo? I'd really appreciate it and i know there are more people rather wanting to use signal without having gapps installed.

**Comment by xmikos** [comment]
Hello, I am going to push LibreSignal update soon today (only official sources from main repo, WebSocket fork hasn't been updated yet).

I am trying to review all code diffs between Signal versions before pushing update and sometimes it takes me more time than I have. But I will try to push updates sooner.

**Comment by thrillfall** [comment]
Thank you very much! Glad that you keep up the great work
