### ISSUE TITLE
Repository fingerprint

### ISSUE THREAD

**Issue by eNTi** [xmikos/fdroiddata#20]
Could you provide a fingerprint please?

**Comment by xmikos** [comment]
Fingerprint is part of repository URL, e.g.:

`https://eutopia.cz/fdroid/repo?fingerprint=A0E4D1D912D8B81809AB18F5B7CF562CD1A10533ED4F7B25E595ABC8D862AD87`

If you click on link to repo in web browser on Android device and choose F-Droid app to open it (it will ask you), repo will be automatically added to F-Droid with fingerprint pre-filled.
