### ISSUE TITLE
Is LibreSignal dead or not?

### ISSUE THREAD

**Issue by idumych** [xmikos/fdroiddata#24]
The LibreSignal github page currently states the following:

The project was abandoned because of https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165

What does that mean for the future of builds on this repo?

**Comment by xmikos** [comment]
LibreSignal (WebSocket-fork, build from sources on https://github.com/LibreSignal/LibreSignal) is pretty much dead. Just now I have uploaded update to my _experimental_ repo on https://fdroid.eutopia.cz, but it could be last update. But there is some new hope that WebSocket support will be added to official Signal in the future (see here: https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-226646872), which would be really great.

Keep in mind that I am still providing (and will definitely provide in the future) independent builds from official Signal sources in my _main_ repo on https://fdroid.eutopia.cz.

**Comment by razzor1984** [comment]
Hello, is that the last websocket build? How long will it work. Are there limitations at the server side, if a certain signal version is outdated ? (Is that the reason why we got the countdown message "will stop working in X days")

The hope for a build in websocket version will take how long? Because i dont have gaps installed on my device, manly privacy concerns. There is now a kind of work around present, the https://microg.org/ projects delivers an open-source implementation, of a big bunch of the google apis. 
At the end, it uses google servers, an thats a reason why i find this not the ideal way.
best regards 
Razzor

**Comment by xmikos** [comment]
@razzor1984 I would like to provide builds of WebSocket-fork untill there is better solution available (which probably will be new version of ChatSecure and/or Zom with OMEMO support - it must be available on both Android and iOS, use encryption by default, have encrypted group chats and it must be user friendly/really simple to configure). But it depends on [LibreSignal](https://github.com/LibreSignal/LibreSignal) GitHub repository still being updated, which is really uncertain. So it probably is last build...

Btw. microG is IMHO good solution, if some agency would want to collect Signal users metadata, Signal servers are much better target than Google GCM (there is not much metadata they would be able to collect on GCM servers).

**Comment by razzor1984** [comment]
@xmikos - Ok so you bought use some time, but if the repo of libre signal will be discontinued, the only way to get on an non Google playstore version(it will disappear from fdroid, i guess), is to build it yourselve (from the source) :(

I appreciate that Chatsecure and Conversation implement the OMEMO support, in the near future it will "hopefully" become more user friendly (guided account implementation - you need the simplest approach at all)
The biggest concern is, if you have a certain stock amount of users by messenger x, its kind of a leverage to use this messenger. Why is Whats app so popular ? The users are the stock Value, and thats the reason why so many use it. If you give the people a choice i would say a good amount would turn head on Whats app !!!!

 Its easy to say: Lets change your messenger, but you loose a good amount of contacts by this transition step.
Thats also my problem, a big bunch of my contacts use Signal, i simply cant say: guys please change the messenger to - X (from this stand point i would recommend - Conversations ) I have three options, abandon Signal at all an live with that, or change to microG or change to an XMPP bases messenger like Conversations.
Why i cant change the messenger is simple, the contacts which will not follow to the new messenger, contact me, or i them through SMS, which is a privacy disaster next to hell. So the best trade off would be microG, but i have no idea how good the implementation is and will it even work ?

best regards Razzor

**Comment by ClubWDW** [comment]
I have wondered about the privacy in MicroG. I know it is open source, but what I go gets passed to Google when used?

**Comment by 5chdn** [comment]
HI @xmikos, it seems libresignal does not install anymore from your fdroid repo. I'm getting:

> Error installing LibreSignal (WebSocket)
> 
> Permissions of the apk file are not a true subset of the permissions listed by the repo, i.e., some permissions have not been shown to the user!

Any idea why this happens? Tested this on two different devices.

**Comment by mimi89999** [comment]
@5chdn F-Droid has a more strict permission check policy now.

**Comment by scytho** [comment]
My LibreSignal (WS) tells me, it’s going to be out of date within nine days. So, is it definitely dead, now? Now that I got most of my contacts using Signal, and Signal Desktop working, including updates.

**Comment by 5chdn** [comment]
> @5chdn F-Droid has a more strict permission check policy now.

Still does not work. I unregistered my Signal account for now. No chance to get it working from F-Droid anymore :-(

**Comment by xmikos** [comment]
@5chdn Don't you have bad version of F-Droid? Latest stable version is 0.100.1 and there it works without problems. Alpha versions (0.101-alphaX) has been broken for some time:

[Issue #703: Can't install any apps that require permissions](https://gitlab.com/fdroid/fdroidclient/issues/703)

But according to that issue, it should be fixed now.

**Comment by 5chdn** [comment]
Thanks for the pointer, will have a look at it (just checked, having the alpha version).
