### ISSUE TITLE
LibreSignal 3.16.0 about to expire

### ISSUE THREAD

**Issue by nicolasmueller** [xmikos/fdroiddata#25]
My installation of LibreSignal 3.16.0 from https://eutopia.cz/fdroid/repo tells me that it will expire in 7 days. This issue was present in Signal 3.16.0 and is solved in Signal 3.16.1, so it would be good if the new upstream release would be used.

Thanks for your builds anyway!

**Comment by mimi89999** [comment]
I pulled the version bump from upstream to the LibreSignal repo.

**Comment by nicolasmueller** [comment]
This doesn't soolve this issue because I'm relying on the independent builds of Signal by @xmikos in the main repo of https://eutopia.cz/froid (I'm using Signal with microg to replace Google Play)
Now it's only 4 days till it will expire. Is this repository abandoned, or will updates be published?

**Comment by xmikos** [comment]
It is not abandoned, I will release new builds this evening or tomorrow. Sorry for delay, vacation :-)

**Comment by nicolasmueller** [comment]
@xmikos : now it's only one day.. If it's not updated very soon, I will build my own version of Signal and not use or recommend the repo again. Thanks for providing it, while it lasted.

**Comment by ingerling** [comment]
@xmikos Is there anything I could do to help? 
I'm also relying on the fdroid main repo and waiting desperately for the update :)
Unfortunately I don't have experience with building android apps myself.

**Comment by tecufanujacu** [comment]
@nicolasmueller me too I had used this repo for LibreSignal and I had problems with the updates. Me too I'm using microg and I decided to install the blankstore instead of the fakestore to use the original version of Signal.
You can use oandbackup to backup the data of LibreSignal and to restore them after installing Signal.

**Comment by xmikos** [comment]
@nicolasmueller @tecufanujacu Sorry, too little time recently :-( But new version is finally uploaded.

Nevertheless this version age check in Signal is really stupid, there is nothing (not a single line) new in version 3.16.1 in comparison with 3.16.0. It has been released solely to reset countdown timer...

**Comment by mimi89999** [comment]
I could change that, but I don't think it makes any sense since LibreSignal won't be continued.

**Comment by xmikos** [comment]
@mimi89999 Yes, it doesn't make much sense now to change that now that LibreSignal (WebSocket fork) is EOL. And my version in _main_ repository is built from original Signal sources, so I can't (and don't want to) change it even there.
