### ISSUE TITLE
libresignal-websockets build

### ISSUE THREAD

**Issue by greycanary** [xmikos/fdroiddata#28]
Hi xmikos,

First of all: Thanks a lot for your great work and for your nice repo!

I wanted to ask if you're updating libresignal-websockets again.

@mimi89999 updated the LibreSignal repo [LibreSignal#49](https://github.com/LibreSignal/LibreSignal/issues/49), so it should be possible to update libresignal-websockets again.

also there is the Signal Fork [Noise](https://github.com/copperhead/Noise) by copperhead - it works without gcm and could be used for libresignal-websockets as well.

Would be nice if you could keep libresignal-websockets alive until websockets support will land in Signal/libresignal!

**Comment by mimi89999** [comment]
I didn't update it...

**Comment by greycanary** [comment]
@mimi89999 Oh then I missunderstood your post - thought you updated to a prior version...

> Update only to the version before that change/feature was introduced.

thanks for the clarification!

@xmikos is it possible to use Noise as a source for libresignal-websockets?

**Comment by jomo** [comment]
Hi all, you can use [my fork](https://github.com/jomo/LibreSignal-forever) that doesn't expire, it should be compatible with the latest websocket version that was available via the experimental repo.

**Comment by xmikos** [comment]
Latest official version of Signal 3.30.0 should finally work without Google Play Services. Please try it, independent build (LibreSignal) is as usual in my main F-Droid repo on https://fdroid.eutopia.cz
