### ISSUE TITLE
Voice support on LibreSignal

### ISSUE THREAD

**Issue by comzeradd** [xmikos/fdroiddata#33]
It seems that there was a bug on websockets regarding calls, that was just fixed and include on 3.30.3. It probably affects LibreSignal too, so I just wanted to make sure it's under your radar :)

https://github.com/WhisperSystems/Signal-Android/issues/6272

**Comment by xmikos** [comment]
Done (version 3.30.4). Sorry for the delay, I only publish new builds after review of code changes (and I didn't have time to review it earlier).
