### ISSUE TITLE
Permission to reuse fdroid.eutopia.cz html/css

### ISSUE THREAD

**Issue by paride** [xmikos/fdroiddata#35]
Hello,

May I reuse part of the html and css from fdroid.eutopia.cz as a starting point for the webpage of an fdroid repository I'm setting up?

Thank you,
Paride

**Comment by xmikos** [comment]
Of course you can, but be aware that I have myself reused logo and some parts of CSS from official https://f-droid.org website.

**Comment by paride** [comment]
Thank you!
