### ISSUE TITLE
new versions

### ISSUE THREAD

**Issue by ilf** [xmikos/fdroiddata#38]
The version of LibreSignal in the repository is 3.30.4, from Feb 28.

There have been nine Signal releases since then, it is currently at 4.2.1 from yesterday: https://github.com/WhisperSystems/Signal-Android/releases/tag/v4.2.1

It would be great to sync LibreSignal back with the Signal code.

Thanks, and keep up the good work!

**Comment by xmikos** [comment]
Done. I am now building Signal "website" flavor (with autoupdate URL changed from https://updates.signal.org/android/latest.json to https://fdroid.eutopia.cz/updates/libresignal.json).
