### ISSUE TITLE
libresignal-websocket rebuild request

### ISSUE THREAD

**Issue by urandom2** [xmikos/fdroiddata#4]
I realize that this may not be the best way to request this, but your repo is currently on v3.3.1-websocket, and it looks like JavaJens repo merged in [v3.6.1](https://github.com/JavaJens/TextSecure/commit/94b5045bdc1728ad1523a7c9fdab9f5e35eab376) recently, then one pull after than. it would be awesome if you could rebuild to at least v3.6.1

**Comment by xmikos** [comment]
Done, LibreSignal v3.6.1-websocket is uploaded (together with non-websocket v3.8.1 in main repo). Sorry that it took me that long.

**Comment by urandom2** [comment]
thanks, would you like me to post similar requests here or reach you through some other method.
