### ISSUE TITLE
Update to upstream Signal 4.5.2

### ISSUE THREAD

**Issue by xenithorb** [xmikos/fdroiddata#40]
For me this is a critical update as m0xie has finally migrated the echo cancellation to a whitelist, so I suspect I can now use calling again without screeching noises.

Can you please update it? Thanks.

I did read through all of the recent issues regarding updating LibreSignal and the distribution of Signal via F-Droid, and your issues reproducing builds, so I suspect that may have something to do with it being so out of date. Re: #39, I just wanted to say thanks for looking out.

**Comment by xmikos** [comment]
I have published new builds of versions 4.5.3 and 4.6.0.
