### ISSUE TITLE
SMS & MMS format

### ISSUE THREAD

**Issue by FilLupin** [xmikos/fdroiddata#42]
Hello,
is there a documentation of the used format for MMS and SMS?
I would like to understand if I can switch from/to Silence app.
Thank you.

**Comment by FilLupin** [comment]
It seems since LibreSignal is a rebuild of Signal, and Signal abandonned encrypted SMS (https://signal.org/blog/goodbye-encrypted-sms/), LibreSignal does not have any encrypted SMS and MMS format, which would simplify my question.
Someone to confirm?

**Comment by jomo** [comment]
Indeed, LibreSignal is exactly the same as Signal (only the name is changed). As you figured out, Signal abandoned SMS/MMS, so that is no longer going to work with (Libre)Signal.

**Comment by FilLupin** [comment]
Thank you for your answer.
