### ISSUE TITLE
Enable issues for the LibreSignal repo

### ISSUE THREAD

**Issue by pizzamaker** [xmikos/fdroiddata#8]
Sorry this is the wrong place to do it, but I need to report bugs on your fork of TextSecure/LibreSignal.

**Comment by xmikos** [comment]
I am not maintaining WebSocket fork, builds of WebSocket fork in my experimental repository are from sources at https://github.com/JavaJens/TextSecure. My fork of that repository is there only because of one pull request

**Comment by pizzamaker** [comment]
Sorry, I'm a little confused. The JavaJens repo is the source for LibreSignal in eutopia.cz?

**Comment by xmikos** [comment]
JavaJens repo is the source for WebSocket version of LibreSignal in _experimental_ repo. Build in main repo is from official sources by Open Whisper Systems.
