### ISSUE TITLE
New key?

### ISSUE THREAD

**Issue by tastytea** [xmikos/fdroiddata#9]
When I try to update LibreSignal, F-Droid complains that the new version is signed with a different key than the installed version.
I have 3.9.0 installed and trying to install 3.9.1 using https://eutopia.cz/fdroid/repo

**Comment by thrillfall** [comment]
Do you also have the o9i repo installed? If that is the case then this is the origin of the "new key problem"
(this is also mentioned here https://github.com/xmikos/fdroiddata/issues/5)

In short o9i also provides a signal build (signed with a different key). The only way to find out from which repo the build comes from is to look at the identifier on the right side of the version history. For xmikos it shows 'source' and for o9i it shows 'bin'. Thats at least my interpretation of this string.

**Comment by tastytea** [comment]
Yes, this is the problem. Thank you!
